default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: westagilelabs_demo_blog_dev

test:
  <<: *default
  database: westagilelabs_demo_blog_test

production:
  <<: *default
  database: westagilelabs_demo_blog_prod